import os
import subprocess
import sys
import signal
import time
from configparser import ConfigParser

# 解决打包后路径问题：获取exe所在目录
def get_app_path():
    if getattr(sys, 'frozen', False):
        # 打包成exe后的运行目录
        return os.path.dirname(sys.executable)
    else:
        # 开发模式下的运行目录
        return os.path.dirname(os.path.abspath(__file__))

class MinecraftServerManager:
    def __init__(self):
        """初始化服务器管理器，加载配置"""
        self.app_dir = get_app_path()
        self.config_path = os.path.join(self.app_dir, "server_config.ini")
        self.config = ConfigParser()
        self.server_process = None  # 存储服务器进程对象
        self.load_config()

    def load_config(self):
        """加载或初始化配置文件"""
        # 如果配置文件不存在，创建默认配置
        if not os.path.exists(self.config_path):
            self.config['SERVER'] = {
                'server_jar_path': './minecraft_server.jar',  # 服务端jar文件路径
                'java_path': 'java',  # Java路径（系统已配置环境变量则填java即可）
                'max_memory': '2G',   # 最大内存
                'min_memory': '1G',   # 最小内存
                'server_dir': './',   # 服务器工作目录
                'nogui': False        # GUI模式启动
            }
            with open(self.config_path, 'w', encoding='utf-8') as f:
                self.config.write(f)
            print(f"已在 {self.config_path} 创建默认配置文件，请检查配置后重新运行")
            input("按回车键退出...")
            sys.exit(1)
        
        # 读取配置
        self.config.read(self.config_path, encoding='utf-8')
        self.server_jar = self.config['SERVER']['server_jar_path']
        self.java_path = self.config['SERVER']['java_path']
        self.max_mem = self.config['SERVER']['max_memory']
        self.min_mem = self.config['SERVER']['min_memory']
        # 拼接服务器目录（基于exe所在目录）
        self.server_dir = os.path.join(self.app_dir, self.config['SERVER']['server_dir'].strip('./'))
        self.nogui = self.config.getboolean('SERVER', 'nogui')

        # 检查必要文件是否存在
        jar_full_path = os.path.join(self.server_dir, self.server_jar)
        if not os.path.exists(jar_full_path):
            print(f"错误：未找到服务器文件 {jar_full_path}")
            input("按回车键退出...")
            sys.exit(1)

    def auto_agree_eula(self):
        """自动同意Minecraft EULA协议"""
        eula_path = os.path.join(self.server_dir, "eula.txt")
        
        # 如果文件不存在，直接创建并写入eula=true
        if not os.path.exists(eula_path):
            print("未找到eula.txt，自动创建并同意协议...")
            with open(eula_path, 'w', encoding='utf-8') as f:
                f.write("# Generated by Minecraft Server Manager\n")
                f.write("# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).\n")
                f.write("eula=true\n")
        else:
            # 如果文件已存在，读取并修改eula=false为eula=true
            print("检查并更新eula.txt协议状态...")
            with open(eula_path, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            updated_lines = []
            eula_updated = False
            for line in lines:
                if line.strip().startswith('eula='):
                    if line.strip() != 'eula=true':
                        updated_lines.append('eula=true\n')
                        eula_updated = True
                    else:
                        updated_lines.append(line)
                else:
                    updated_lines.append(line)
            
            # 如果需要更新，写入文件
            if eula_updated:
                with open(eula_path, 'w', encoding='utf-8') as f:
                    f.writelines(updated_lines)
                print("已自动同意EULA协议")
            else:
                print("EULA协议已同意，无需修改")

    def start_server(self):
        """启动Minecraft服务器"""
        if self.server_process and self.server_process.poll() is None:
            print("服务器已在运行中！")
            input("按回车键继续...")
            return

        # 启动前自动同意EULA
        self.auto_agree_eula()

        # 构建启动命令
        cmd = [
            self.java_path,
            f'-Xmx{self.max_mem}',
            f'-Xms{self.min_mem}',
            '-jar', self.server_jar
        ]
        if self.nogui:
            cmd.append('nogui')

        print(f"正在启动服务器，命令：{' '.join(cmd)}")
        print("="*50)

        # 启动进程，实时捕获输出
        try:
            self.server_process = subprocess.Popen(
                cmd,
                cwd=self.server_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
                universal_newlines=True,
                creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if sys.platform == 'win32' else 0
            )

            # 实时打印日志
            while self.server_process.poll() is None:
                line = self.server_process.stdout.readline()
                if line:
                    print(line.strip())

            # 检查退出码
            exit_code = self.server_process.returncode
            print(f"\n服务器已停止，退出码：{exit_code}")
            input("按回车键继续...")

        except Exception as e:
            print(f"启动服务器失败：{str(e)}")
            self.stop_server()
            input("按回车键继续...")

    def stop_server(self):
        """停止Minecraft服务器"""
        if not self.server_process or self.server_process.poll() is not None:
            print("服务器未运行！")
            input("按回车键继续...")
            return

        print("正在停止服务器...")
        try:
            # Windows下优雅停止（适配打包后的进程）
            if sys.platform == 'win32':
                # 发送Ctrl+C到子进程组
                os.kill(self.server_process.pid, signal.CTRL_BREAK_EVENT)
            else:
                self.server_process.terminate()
            
            # 等待进程退出
            self.server_process.wait(timeout=10)
            print("服务器已成功停止！")
        except subprocess.TimeoutExpired:
            print("优雅停止超时，强制终止进程...")
            self.server_process.kill()
        except Exception as e:
            print(f"停止服务器失败：{str(e)}")
        finally:
            input("按回车键继续...")

    def is_running(self):
        """检查服务器是否运行"""
        return self.server_process and self.server_process.poll() is None

def signal_handler(signum, frame):
    """信号处理函数，捕获Ctrl+C"""
    print("\n\n接收到停止信号，正在关闭服务器...")
    server_manager.stop_server()
    sys.exit(0)

if __name__ == "__main__":
    # 设置控制台编码（解决Windows下中文乱码）
    if sys.platform == 'win32':
        os.system('chcp 65001 > nul')
    
    # 创建服务器管理器实例
    server_manager = MinecraftServerManager()

    # 注册信号处理（捕获Ctrl+C）
    signal.signal(signal.SIGINT, signal_handler)

    # 命令行交互
    while True:
        os.system('cls' if sys.platform == 'win32' else 'clear')
        print("===== Minecraft 服务器管理器 =====")
        print("1. 启动服务器")
        print("2. 停止服务器")
        print("3. 退出")
        print("==================================")
        
        choice = input("\n请输入操作编号（1/2/3）：")
        if choice == '1':
            server_manager.start_server()
        elif choice == '2':
            server_manager.stop_server()
        elif choice == '3':
            if server_manager.is_running():
                confirm = input("服务器仍在运行，确定退出吗？(y/n)：")
                if confirm.lower() == 'y':
                    server_manager.stop_server()
                    break
            else:
                break
        else:
            print("无效的选择，请输入1、2或3！")
            input("按回车键继续...")

    print("服务器管理器已退出")